#!/bin/bash/

FILE="$HOME/songapp/songs_dataset.csv"

listArtists() {
	if [[ "$1" = "az" ]]
	then
		cat "$FILE" | cut -f 2,4 --output-delimiter="-" | awk -F "-" '{printf "%s-%s\n", $2, $1}' | sed -e 's/^[[:space:]]*//' | sort -f | awk -F "-" '{printf "%-75s - - %s\n", $1, $2}' | less
	fi

	if [[ "$1" = "za" ]]
	then
		cat "$FILE" | cut -f 2,4 --output-delimiter="-" | awk -F "-" '{printf "%s-%s\n", $2, $1}' | sed -e 's/^[[:space:]]*//' | sort -f -r | awk -F "-" '{printf "%-75s - - %s\n", $1, $2}' | less
	fi
}

hep() {
	echo "Usage:"
	echo "artist_sort <OPTION>"
	echo "             az      - Sort by artist alphabetically"
	echo "             za      - Sort by artist reverse alphabetically"
}

if [[ -z "$1" ]]
then
	hep
else
	listArtists "$@"
fi
