#!/bin/bash

FILE="$HOME/songapp/songs_dataset.csv"

sorting() {
        reverse=""
        if [[ "$1" = "high" ]]
        then
		cat "$FILE" | cut -d $'\t' -f 2,5 | sort -r -k 2 -t $'\t' -h
	else 
		if [[ "$1" = "low" ]]
		then
			cat "$FILE" | cut -d $'\t' -f 2,5 | sort -k 2 -t $'\t' -h
		fi
        fi


}

hep() {
	echo "Usage:"
	echo "./pop_sort <OPTION>"
	echo
	echo "	    high:	display from highest popularity to lowest"
	echo "	    low:	display from lowest popularity to highest"
}

if [[ -z "$1" ]]
then
	hep
else
	sorting "$@" | less
fi

